Logo design
hot9cups/website-for-friend pull request #3
Opened 2020-10-01 05:26 UTC by Sharps

Regarding #2

Here's a logo design, wasn't sure how literally you wanted the "hardware data recovery" highlighted, so I put the actual text there. It's very simple and generic but it might work or give you some ideas.

2020-10-01 06:10 UTC, hot9cups requested changes
Hey @Sharps 

Thanks for taking an interest in the issue.

I like the logo, it's simple and quite good. 
There's a few modifications I'd like you to make though:
1)Right now, the background is black and the font color of "Dynamic Technologies" is a dark shade of gray. That makes it a little difficult to read it, could you come up with a better color contrast?
2)Could you change "Hardware Data Recovery" to "Hard-Disk Data Recovery" as well as increase its font by a notch?

Other than that, you've done a good job!

2020-10-01 06:20 UTC, Sharps commented
This should work much better for black backgrounds.

2020-10-02 07:44 UTC, hot9cups approved these changes

2020-10-02 07:45 UTC, merged

2020-10-02 07:45 UTC, hot9cups commented
This is good, thanks for your contribution @Sharps